### ISSUE TITLE
Not displayed menu

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/fe#224]
**Preconditions:** DB must be filled.

**AR:**
![- google chrome_013](https://cloud.githubusercontent.com/assets/18617219/17962641/769beed8-6aba-11e6-8e16-0ee2602b09c7.png)

**ER:** Menus must be shown.

**Comment by dezoxel** [comment]
Done. @Kostya47 please test. Please pay attention that I've added fail overs where there is no menu cover and there are no prices defined. Such issue happened because of absence images and price for menu.

Current expected behavior with fail overs:
- When menu doesn't have image - image is not shown.
- When menu doesn't have prices - impossible to place order.

In order to fix this issue eventually, you have to fill in the DB with images and prices.

**Comment by Kostya47** [comment]
Verified.
